//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.AssignCourses = new HashSet<AssignCourse>();
            this.Topics = new HashSet<Topic>();
        }

        [Display(Name = "Course Id")]
        public int CourseId { get; set; }

        [Required(ErrorMessage = "The Course name cannot be left blank")]
        [Display(Name = "Course name")]
        public string Course_name { get; set; }

        [Display(Name = "Description")]
        public string Course_description { get; set; }

        public string image { get; set; }

        public List<Course> CourseCollection { get; set; }

        [Display(Name = "Category")]
        public Nullable<int> CategoryId { get; set; }

        [Display(Name = "Time to start")]
        public Nullable<System.DateTime> DateToStart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignCourse> AssignCourses { get; set; }
        public virtual CourseCategory CourseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
