//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.AssignTopics = new HashSet<AssignTopic>();
        }

        [Display(Name = "Topic Id")]
        public int TopicId { get; set; }

        [Required(ErrorMessage = "The Topic name cannot be left blank")]
        [Display(Name = "Topic name")]
        public string Topic_name { get; set; }

        [Display(Name = "Description")]
        public string Topic_description { get; set; }
        public string image { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignTopic> AssignTopics { get; set; }
        public virtual Course Course { get; set; }
    }
}
