//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.AssignCourses = new HashSet<AssignCourse>();
        }

        [Required(ErrorMessage = "The Id cannot be left blank")]
        [Display(Name = "Trainee id")]
        public string TraineeId { get; set; }

        [Required(ErrorMessage = "The Username cannot be left blank")]
        [Display(Name = "Username")]
        public string Trainee_username { get; set; }

        [RegularExpression(
            "^((?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])|(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[^a-zA-Z0-9])|(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[^a-zA-Z0-9])|(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^a-zA-Z0-9])).{8,}$",
            ErrorMessage = "Passwords must be at least 8 characters and contain at 3 of 4 of the following: upper case (A-Z), lower case (a-z), number (0-9) and special character (e.g. !@#$%^&*)"
            )]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "The Password cannot be left blank")]
        public string Trainee_password { get; set; }

        [Required(ErrorMessage = "The Fullname cannot be left blank")]
        [Display(Name = "Trainee fullname")]
        public string Trainee_fullname { get; set; }

        [Display(Name = "Age")]
        public Nullable<int> Trainee_age { get; set; }

        [Display(Name = "Birthday")]
        public Nullable<System.DateTime> Trainee_birthday { get; set; }

        [Display(Name = "Education")]
        public string Trainee_education { get; set; }

        [Display(Name = "Programming language")]
        public string Trainee_programming_language { get; set; }

        [Display(Name = "TOEIC scrore")]
        public Nullable<int> Trainee_TOEIC_score { get; set; }

        [Display(Name = "Experience details")]
        public string Trainee_exprience_details { get; set; }

        [Display(Name = "Department")]
        public string Trainee_department { get; set; }

        [Display(Name = "Location")]
        public string Trainee_location { get; set; }
        public string image { get; set; }

        [Display(Name = "Confirm password")]
        [DataType(DataType.Password)]
        [Compare("Trainee_password", ErrorMessage = "Confirm password does not match")]
        public string ConfirmPassword { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignCourse> AssignCourses { get; set; }
    }
}
